#!/usr/bin/env python3
"""Tiny local bank reserve signer fixture for Cellshire testnet smoke flows.

This is not a private-key signer. It is a deterministic fixture endpoint for
exercising the frontend `chainBankReserveSignerUrl` path while the real bank
backend and deployed scripts are still being built.

Run:

    python3 scripts/bank_reserve_signer_fixture.py --port 8791

Production smoke bundles can be generated by supplying deployed script params
and real backend URLs:

    python3 scripts/bank_reserve_signer_fixture.py --validate-production-smoke \
        --deployment-values-json bank-testnet-values.json

    python3 scripts/bank_reserve_signer_fixture.py --validate-production-smoke \
        --deployment-values-json bank-testnet-values.json \
        --write-smoke-report bank-testnet-smoke-report.json

or:

    python3 scripts/bank_reserve_signer_fixture.py --validate-production-smoke \
        --script-params-json bank-scripts.json \
        --bank-borrow-input-provider-url https://bank.example/borrow-inputs \
        --bank-repay-input-provider-url https://bank.example/repay-inputs \
        --bank-reserve-signer-url https://bank.example/sign

    python3 scripts/bank_reserve_signer_fixture.py --production-smoke \
        --script-params-json bank-scripts.json \
        --bank-borrow-input-provider-url https://bank.example/borrow-inputs \
        --bank-repay-input-provider-url https://bank.example/repay-inputs \
        --bank-reserve-signer-url https://bank.example/sign

Useful endpoints:

    GET  /health
    GET  /reserve-inputs
    GET  /smoke-params
    POST /borrow-inputs
    POST /repay-inputs
    POST /sign

The frontend should point `chainBankReserveSignerUrl` at `/sign`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass, field, replace
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any
from urllib.parse import parse_qs, parse_qsl, urlencode, urlparse


DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8791
DEFAULT_RESERVE_AMOUNT_CKB = 100_000
DEFAULT_RESERVE_TX_HASH = "0x" + ("71" * 32)
DEFAULT_RESERVE_INDEX = 0
DEFAULT_COLLATERAL_AMOUNT_CKB = 11_250
DEFAULT_COLLATERAL_TX_HASH = "0x" + ("72" * 32)
DEFAULT_COLLATERAL_INDEX = 1
DEFAULT_DEBT_TX_HASH = "0x" + ("73" * 32)
DEFAULT_DEBT_INDEX = 0
DEFAULT_LOCKED_COLLATERAL_TX_HASH = "0x" + ("74" * 32)
DEFAULT_LOCKED_COLLATERAL_INDEX = 2
BANK_RESERVE_SIGNER_RESPONSE_PROTOCOL = "cellshire.bank.reserve-sign.response"
BANK_INPUT_PROVIDER_RESPONSE_PROTOCOL = "cellshire.bank.inputs.response"
SMOKE_SCRIPT_PARAMS = {
    "chainBankDebtTypeCodeHash": "0x" + ("11" * 32),
    "chainBankBookLockCodeHash": "0x" + ("22" * 32),
    "chainBankCollateralLockCodeHash": "0x" + ("33" * 32),
    "chainBankReserveLockCodeHash": "0x" + ("44" * 32),
    "chainBankTreasuryLockCodeHash": "0x" + ("55" * 32),
}
REQUIRED_SCRIPT_PARAM_KEYS = (
    "chainBankDebtTypeCodeHash",
    "chainBankBookLockCodeHash",
    "chainBankCollateralLockCodeHash",
    "chainBankReserveLockCodeHash",
    "chainBankTreasuryLockCodeHash",
)
SCRIPT_DEP_PREFIXES = (
    "chainBankDebtTypeDep",
    "chainBankBookLockDep",
    "chainBankCollateralLockDep",
    "chainBankReserveLockDep",
    "chainBankTreasuryLockDep",
)
HASH_RE = re.compile(r"^0x[0-9a-fA-F]{64}$")
TOKEN_KEYS = {
    "chainBankInputProviderToken",
    "chainBankReserveSignerToken",
    "token",
}


@dataclass(frozen=True)
class FixtureConfig:
    host: str = DEFAULT_HOST
    port: int = DEFAULT_PORT
    reserve_tx_hash: str = DEFAULT_RESERVE_TX_HASH
    reserve_index: int = DEFAULT_RESERVE_INDEX
    reserve_amount_ckb: float = DEFAULT_RESERVE_AMOUNT_CKB
    collateral_tx_hash: str = DEFAULT_COLLATERAL_TX_HASH
    collateral_index: int = DEFAULT_COLLATERAL_INDEX
    debt_tx_hash: str = DEFAULT_DEBT_TX_HASH
    debt_index: int = DEFAULT_DEBT_INDEX
    locked_collateral_tx_hash: str = DEFAULT_LOCKED_COLLATERAL_TX_HASH
    locked_collateral_index: int = DEFAULT_LOCKED_COLLATERAL_INDEX
    script_params: dict[str, str] = field(default_factory=lambda: dict(SMOKE_SCRIPT_PARAMS))
    input_provider_url: str = ""
    borrow_input_provider_url: str = ""
    repay_input_provider_url: str = ""
    reserve_signer_url: str = ""
    production_smoke: bool = False
    bank_reserve_cells: list[dict[str, Any]] = field(default_factory=list)
    borrower_collateral_cells: list[dict[str, Any]] = field(default_factory=list)
    require_deployment_values: bool = False
    token: str = ""


def reserve_input_params(config: FixtureConfig) -> dict[str, Any]:
    return {
        "chainBankReserveCellTxHash": config.reserve_tx_hash,
        "chainBankReserveCellIndex": str(config.reserve_index),
        "chainBankReserveCellCapacityCkb": str(config.reserve_amount_ckb),
        "chainBankReserveCellAmountCkb": str(config.reserve_amount_ckb),
    }


def reserve_cell(config: FixtureConfig) -> dict[str, Any]:
    return {
        "outPoint": {
            "txHash": config.reserve_tx_hash,
            "index": config.reserve_index,
        },
        "capacity": config.reserve_amount_ckb,
        "amount": config.reserve_amount_ckb,
    }


def collateral_cell(config: FixtureConfig, amount_ckb: float = DEFAULT_COLLATERAL_AMOUNT_CKB) -> dict[str, Any]:
    return {
        "outPoint": {
            "txHash": config.collateral_tx_hash,
            "index": config.collateral_index,
        },
        "capacity": amount_ckb,
        "amount": amount_ckb,
    }


def debt_cell(config: FixtureConfig) -> dict[str, Any]:
    return {
        "outPoint": {
            "txHash": config.debt_tx_hash,
            "index": config.debt_index,
        },
        "capacity": 61,
        "amount": 61,
    }


def locked_collateral_cell(config: FixtureConfig, amount_ckb: float = DEFAULT_COLLATERAL_AMOUNT_CKB) -> dict[str, Any]:
    return {
        "outPoint": {
            "txHash": config.locked_collateral_tx_hash,
            "index": config.locked_collateral_index,
        },
        "capacity": amount_ckb,
        "amount": amount_ckb,
    }


def signer_url(config: FixtureConfig) -> str:
    return f"http://{config.host}:{config.port}/sign"


def borrow_inputs_url(config: FixtureConfig) -> str:
    return f"http://{config.host}:{config.port}/borrow-inputs"


def repay_inputs_url(config: FixtureConfig) -> str:
    return f"http://{config.host}:{config.port}/repay-inputs"


def smoke_params(config: FixtureConfig) -> dict[str, Any]:
    params = {
        "chainBank": "1",
        "chainBankCollateral": "ckb",
        "chainBankSubmit": "ccc-real",
        "chainCurrencyCkb": "30000",
        "wallet": "joyid",
        "chainBankReserveSignerUrl": config.reserve_signer_url or signer_url(config),
        **config.script_params,
    }
    if config.input_provider_url:
        params["chainBankInputProviderUrl"] = config.input_provider_url
    elif config.borrow_input_provider_url:
        params["chainBankBorrowInputProviderUrl"] = config.borrow_input_provider_url
    else:
        params["chainBankInputProviderUrl"] = borrow_inputs_url(config)
    if config.repay_input_provider_url:
        params["chainBankRepayInputProviderUrl"] = config.repay_input_provider_url
    elif not config.input_provider_url:
        params["chainBankRepayInputProviderUrl"] = repay_inputs_url(config)
    if config.production_smoke:
        params["chainBankScriptMode"] = "production"
    if config.token:
        params["chainBankInputProviderToken"] = config.token
        params["chainBankReserveSignerToken"] = config.token
    return params


def smoke_config(config: FixtureConfig, game_url: str = "") -> dict[str, Any]:
    params = smoke_params(config)
    query = urlencode(params)
    body = {
        "params": params,
        "queryString": query,
    }
    if game_url:
        separator = "&" if "?" in game_url else "?"
        body["url"] = f"{game_url}{separator}{query}"
    return body


def smoke_execution_report(config: FixtureConfig, smoke: dict[str, Any]) -> dict[str, Any]:
    return {
        "protocol": "cellshire.bank.testnet-smoke.report",
        "version": 1,
        "createdAt": datetime.now(timezone.utc).isoformat(),
        "status": "ready-for-manual-execution",
        "smokeBundle": redact_tokens(smoke),
        "deployment": {
            "productionSmoke": True,
            "scriptParamKeys": sorted(config.script_params.keys()),
            "bankReserveCellCount": len(config.bank_reserve_cells),
            "borrowerCollateralCellCount": len(config.borrower_collateral_cells),
            "hasSharedInputProvider": bool(config.input_provider_url),
            "hasBorrowInputProvider": bool(config.borrow_input_provider_url),
            "hasRepayInputProvider": bool(config.repay_input_provider_url),
            "hasReserveSigner": bool(config.reserve_signer_url),
        },
        "evidence": {
            "preflight": {
                "validated": True,
                "issues": [],
            },
            "borrow": {
                "status": "pending",
                "txHash": "",
                "bankReserveInput": "",
                "collateralInput": "",
                "backendRequestId": "",
                "notes": "",
            },
            "indexerAfterBorrow": {
                "status": "pending",
                "debtOutPoint": "",
                "lockedCollateralOutPoint": "",
                "notes": "",
            },
            "repay": {
                "status": "pending",
                "txHash": "",
                "debtInput": "",
                "lockedCollateralInput": "",
                "backendRequestId": "",
                "notes": "",
            },
            "indexerAfterRepay": {
                "status": "pending",
                "debtConsumed": False,
                "collateralReleased": False,
                "walletPendingCleared": False,
                "notes": "",
            },
        },
    }


def redact_tokens(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            key: redact_query_string(item) if key == "queryString" and isinstance(item, str)
            else ("<redacted>" if key in TOKEN_KEYS and item else redact_tokens(item))
            for key, item in value.items()
        }
    if isinstance(value, list):
        return [redact_tokens(item) for item in value]
    return value


def redact_query_string(value: str) -> str:
    pairs = []
    for key, item in parse_qsl(value, keep_blank_values=True):
        pairs.append((key, "<redacted>" if key in TOKEN_KEYS and item else item))
    return urlencode(pairs)


def build_bank_witness(request: dict[str, Any], config: FixtureConfig) -> str:
    payload = request.get("payload") or {}
    tx = request.get("tx") or {}
    reserve_input = find_reserve_input(tx, config)
    if request.get("protocol") != "cellshire.bank.reserve-sign":
        raise ValueError("invalid-protocol")
    if request.get("action") != "borrow" and payload.get("action") != "borrow":
        raise ValueError("unsupported-action")
    if not reserve_input:
        raise ValueError("reserve-input-missing")
    if not payload.get("tx_nonce"):
        raise ValueError("missing-tx-nonce")

    body = {
        "protocol": "cellshire.bank.reserve-witness.fixture",
        "version": 1,
        "action": "borrow",
        "tx_nonce": payload["tx_nonce"],
        "offer_id": payload.get("offer_id"),
        "principal": payload.get("principal"),
        "reserve_outpoint": reserve_input["previousOutput"],
        "digest": request_digest(request),
    }
    return "0x" + json.dumps(body, sort_keys=True, separators=(",", ":")).encode("utf-8").hex()


def find_reserve_input(tx: dict[str, Any], config: FixtureConfig) -> dict[str, Any] | None:
    expected = {
        "txHash": config.reserve_tx_hash.lower(),
        "index": config.reserve_index,
    }
    for item in tx.get("inputs") or []:
        prev = item.get("previousOutput") or {}
        if str(prev.get("txHash", "")).lower() == expected["txHash"] and int(prev.get("index", -1)) == expected["index"]:
            return item
    return None


def request_digest(request: dict[str, Any]) -> str:
    encoded = json.dumps(request, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return "0x" + hashlib.sha256(encoded).hexdigest()


def number_or(value: Any, fallback: float) -> float:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return fallback
    return number


def success(body: dict[str, Any], status: int = 200) -> tuple[int, dict[str, Any]]:
    return status, {"ok": True, **body}


def failure(reason: str, status: int = 400) -> tuple[int, dict[str, Any]]:
    return status, {"ok": False, "reason": reason}


def handle_sign(request: dict[str, Any], config: FixtureConfig) -> tuple[int, dict[str, Any]]:
    try:
        return success({
            "protocol": BANK_RESERVE_SIGNER_RESPONSE_PROTOCOL,
            "version": 1,
            "bankWitness": build_bank_witness(request, config),
            "reserveCell": reserve_cell(config),
        })
    except ValueError as err:
        return failure(str(err))


def handle_borrow_inputs(request: dict[str, Any], config: FixtureConfig) -> tuple[int, dict[str, Any]]:
    if request.get("protocol") != "cellshire.bank.inputs.select":
        return failure("invalid-protocol")
    if request.get("action") != "borrow":
        return failure("unsupported-action")
    wallet = request.get("walletAccount") or {}
    if not wallet.get("address"):
        return failure("missing-wallet")
    collateral_amount = number_or(request.get("collateralAmount"), DEFAULT_COLLATERAL_AMOUNT_CKB)
    if collateral_amount <= 0:
        return failure("invalid-collateral")
    return success({
        "protocol": BANK_INPUT_PROVIDER_RESPONSE_PROTOCOL,
        "version": 1,
        "borrow": {
            "bankReserveCell": reserve_cell(config),
            "collateralCell": collateral_cell(config, collateral_amount),
        },
    })


def handle_repay_inputs(request: dict[str, Any], config: FixtureConfig) -> tuple[int, dict[str, Any]]:
    if request.get("protocol") != "cellshire.bank.inputs.select":
        return failure("invalid-protocol")
    if request.get("action") != "repay":
        return failure("unsupported-action")
    wallet = request.get("walletAccount") or {}
    loan = request.get("loan") or {}
    if not wallet.get("address"):
        return failure("missing-wallet")
    if not loan.get("id"):
        return failure("missing-loan")
    collateral_amount = number_or(loan.get("collateralAmount"), DEFAULT_COLLATERAL_AMOUNT_CKB)
    return success({
        "protocol": BANK_INPUT_PROVIDER_RESPONSE_PROTOCOL,
        "version": 1,
        "repay": {
            "debtCell": debt_cell(config),
            "lockedCollateralCell": locked_collateral_cell(config, collateral_amount),
        },
    })


class FixtureHandler(BaseHTTPRequestHandler):
    server_version = "CellshireBankReserveFixture/1.0"

    def do_OPTIONS(self) -> None:
        self._send_json(204, {})

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/health":
            self._send_json(*success({
                "service": "cellshire-bank-reserve-signer-fixture",
            }))
        elif parsed.path == "/reserve-inputs":
            self._send_json(*success({
                "borrow": {
                    "bankReserveCell": reserve_cell(self.server.config),
                },
                "params": reserve_input_params(self.server.config),
            }))
        elif parsed.path == "/smoke-params":
            query = parse_qs(parsed.query)
            game_url = (query.get("game") or [""])[0]
            self._send_json(*success(smoke_config(self.server.config, game_url)))
        else:
            self._send_json(*failure("not-found", 404))

    def do_POST(self) -> None:
        if self.server.config.token:
            expected = f"Bearer {self.server.config.token}"
            if self.headers.get("authorization") != expected:
                self._send_json(*failure("unauthorized", 401))
                return

        parsed = urlparse(self.path)
        if parsed.path not in {"/sign", "/borrow-inputs", "/repay-inputs"}:
            self._send_json(*failure("not-found", 404))
            return

        try:
            length = int(self.headers.get("content-length") or 0)
            body = self.rfile.read(length).decode("utf-8")
            request = json.loads(body or "{}")
        except (UnicodeDecodeError, json.JSONDecodeError):
            self._send_json(*failure("invalid-json"))
            return

        if parsed.path == "/sign":
            self._send_json(*handle_sign(request, self.server.config))
        elif parsed.path == "/borrow-inputs":
            self._send_json(*handle_borrow_inputs(request, self.server.config))
        else:
            self._send_json(*handle_repay_inputs(request, self.server.config))

    def log_message(self, fmt: str, *args: Any) -> None:
        sys.stderr.write("[bank-reserve-fixture] " + fmt % args + "\n")

    def _send_json(self, status: int, body: dict[str, Any]) -> None:
        data = b"" if status == 204 else json.dumps(body, sort_keys=True).encode("utf-8")
        self.send_response(status)
        self.send_header("access-control-allow-origin", "*")
        self.send_header("access-control-allow-methods", "GET, POST, OPTIONS")
        self.send_header("access-control-allow-headers", "authorization, content-type")
        self.send_header("content-type", "application/json")
        self.send_header("content-length", str(len(data)))
        self.end_headers()
        if data:
            self.wfile.write(data)


class FixtureServer(ThreadingHTTPServer):
    def __init__(self, server_address: tuple[str, int], handler: type[BaseHTTPRequestHandler], config: FixtureConfig):
        super().__init__(server_address, handler)
        self.config = config


def sample_sign_request(config: FixtureConfig) -> dict[str, Any]:
    return {
        "protocol": "cellshire.bank.reserve-sign",
        "version": 1,
        "action": "borrow",
        "payload": {
            "action": "borrow",
            "tx_nonce": "bank-borrow-fixture",
            "offer_id": "starter-float",
            "principal": 7500,
        },
        "tx": {
            "inputs": [{
                "since": "0x0",
                "previousOutput": {
                    "txHash": config.reserve_tx_hash,
                    "index": config.reserve_index,
                },
            }],
            "outputs": [],
            "outputsData": [],
            "cellDeps": [],
            "witnesses": ["0x"],
        },
    }


def load_json_file(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def load_script_params(path: str) -> dict[str, str]:
    if not path:
        return dict(SMOKE_SCRIPT_PARAMS)
    return script_params_from_json(load_json_file(path), "script-params-json")


def script_params_from_json(loaded: Any, label: str = "script params") -> dict[str, str]:
    source = loaded.get("params") if isinstance(loaded, dict) and isinstance(loaded.get("params"), dict) else loaded
    if isinstance(loaded, dict) and isinstance(loaded.get("scriptParams"), dict):
        source = loaded["scriptParams"]
    if not isinstance(source, dict):
        raise ValueError(f"{label} must be a JSON object")
    params: dict[str, str] = {}
    for key, value in source.items():
        if not str(key).startswith("chainBank"):
            continue
        if value is None:
            continue
        params[str(key)] = str(value)
    return params


def load_deployment_values(path: str) -> dict[str, Any]:
    if not path:
        return {}
    loaded = load_json_file(path)
    if not isinstance(loaded, dict):
        raise ValueError("deployment-values-json must be a JSON object")
    return loaded


def backend_value(values: dict[str, Any], key: str) -> str:
    backend = values.get("backend") if isinstance(values.get("backend"), dict) else {}
    value = backend.get(key) or values.get(key) or ""
    return str(value) if value is not None else ""


def deployment_cells(values: dict[str, Any], key: str, fallback_key: str = "") -> list[dict[str, Any]]:
    funding = values.get("funding") if isinstance(values.get("funding"), dict) else {}
    raw = funding.get(key)
    if raw is None and fallback_key:
        raw = funding.get(fallback_key)
    if raw is None:
        raw = values.get(key)
    if raw is None:
        return []
    if isinstance(raw, dict):
        raw = [raw]
    if not isinstance(raw, list):
        return []
    return [item for item in raw if isinstance(item, dict)]


def production_smoke_issues(config: FixtureConfig) -> list[str]:
    issues: list[str] = []
    if not (config.input_provider_url or config.borrow_input_provider_url):
        issues.append("missing-production-borrow-input-provider-url")
    elif config.input_provider_url and not valid_url(config.input_provider_url):
        issues.append("invalid-production-input-provider-url")
    elif config.borrow_input_provider_url and not valid_url(config.borrow_input_provider_url):
        issues.append("invalid-production-borrow-input-provider-url")
    if not (config.input_provider_url or config.repay_input_provider_url):
        issues.append("missing-production-repay-input-provider-url")
    elif config.repay_input_provider_url and not valid_url(config.repay_input_provider_url):
        issues.append("invalid-production-repay-input-provider-url")
    if not config.reserve_signer_url:
        issues.append("missing-production-reserve-signer-url")
    elif not valid_url(config.reserve_signer_url):
        issues.append("invalid-production-reserve-signer-url")
    for key in REQUIRED_SCRIPT_PARAM_KEYS:
        if not config.script_params.get(key):
            issues.append(f"missing-{key}")
        elif not HASH_RE.match(config.script_params[key]):
            issues.append(f"invalid-{key}")
    placeholder_values = set(SMOKE_SCRIPT_PARAMS.values())
    for key in REQUIRED_SCRIPT_PARAM_KEYS:
        if config.script_params.get(key) in placeholder_values:
            issues.append(f"placeholder-{key}")
    if not any(config.script_params.get(f"{prefix}TxHash") for prefix in SCRIPT_DEP_PREFIXES):
        issues.append("missing-bank-script-cell-dep")
    for prefix in SCRIPT_DEP_PREFIXES:
        tx_hash = config.script_params.get(f"{prefix}TxHash")
        if tx_hash and not HASH_RE.match(tx_hash):
            issues.append(f"invalid-{prefix}TxHash")
        index = config.script_params.get(f"{prefix}Index")
        if index is not None and not non_negative_integer(index):
            issues.append(f"invalid-{prefix}Index")
        dep_type = config.script_params.get(f"{prefix}Type")
        if dep_type is not None and dep_type not in {"code", "depGroup"}:
            issues.append(f"invalid-{prefix}Type")
    if config.require_deployment_values and not config.bank_reserve_cells:
        issues.append("missing-funded-bank-reserve-cell")
    issues.extend(funded_cell_issues(config.bank_reserve_cells, "bank-reserve-cell"))
    issues.extend(funded_cell_issues(config.borrower_collateral_cells, "borrower-collateral-cell"))
    return issues


def funded_cell_issues(cells: list[dict[str, Any]], label: str) -> list[str]:
    issues: list[str] = []
    for index, cell in enumerate(cells):
        prefix = f"{label}-{index}"
        out_point = cell.get("outPoint") if isinstance(cell.get("outPoint"), dict) else cell
        tx_hash = out_point.get("txHash") or out_point.get("tx_hash")
        if not tx_hash:
            issues.append(f"missing-{prefix}-tx-hash")
        elif not HASH_RE.match(str(tx_hash)):
            issues.append(f"invalid-{prefix}-tx-hash")
        raw_index = out_point.get("index")
        if raw_index is None:
            issues.append(f"missing-{prefix}-index")
        elif not non_negative_integer(str(raw_index)):
            issues.append(f"invalid-{prefix}-index")
        amount = cell.get("amount") if cell.get("amount") is not None else cell.get("capacity")
        if amount is not None and not positive_number(str(amount)):
            issues.append(f"invalid-{prefix}-amount")
    return issues


def valid_url(value: str) -> bool:
    parsed = urlparse(value)
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def non_negative_integer(value: str) -> bool:
    try:
        parsed = int(value)
    except ValueError:
        return False
    return parsed >= 0


def positive_number(value: str) -> bool:
    try:
        parsed = float(value)
    except ValueError:
        return False
    return parsed > 0


def self_test() -> int:
    config = FixtureConfig()
    status, body = handle_borrow_inputs({
        "protocol": "cellshire.bank.inputs.select",
        "version": 1,
        "action": "borrow",
        "walletAccount": {"address": "ckt1fixture"},
        "collateralAmount": DEFAULT_COLLATERAL_AMOUNT_CKB,
    }, config)
    assert status == 200, body
    assert body["protocol"] == BANK_INPUT_PROVIDER_RESPONSE_PROTOCOL
    assert body["borrow"]["bankReserveCell"]["outPoint"]["txHash"] == DEFAULT_RESERVE_TX_HASH
    assert body["borrow"]["collateralCell"]["outPoint"]["txHash"] == DEFAULT_COLLATERAL_TX_HASH

    status, body = handle_repay_inputs({
        "protocol": "cellshire.bank.inputs.select",
        "version": 1,
        "action": "repay",
        "walletAccount": {"address": "ckt1fixture"},
        "loan": {"id": "chain-loan:fixture", "collateralAmount": DEFAULT_COLLATERAL_AMOUNT_CKB},
    }, config)
    assert status == 200, body
    assert body["protocol"] == BANK_INPUT_PROVIDER_RESPONSE_PROTOCOL
    assert body["repay"]["debtCell"]["outPoint"]["txHash"] == DEFAULT_DEBT_TX_HASH
    assert body["repay"]["lockedCollateralCell"]["outPoint"]["txHash"] == DEFAULT_LOCKED_COLLATERAL_TX_HASH

    status, body = handle_sign(sample_sign_request(config), config)
    assert status == 200, body
    assert body["ok"] is True
    assert body["protocol"] == BANK_RESERVE_SIGNER_RESPONSE_PROTOCOL
    assert body["version"] == 1
    assert str(body["bankWitness"]).startswith("0x")

    missing = sample_sign_request(config)
    missing["tx"]["inputs"] = []
    status, body = handle_sign(missing, config)
    assert status == 400, body
    assert body["reason"] == "reserve-input-missing"

    params = reserve_input_params(config)
    assert params["chainBankReserveCellTxHash"] == DEFAULT_RESERVE_TX_HASH
    smoke = smoke_config(config, "http://127.0.0.1:8766/")
    assert smoke["params"]["chainBankSubmit"] == "ccc-real"
    assert smoke["params"]["chainBankInputProviderUrl"] == "http://127.0.0.1:8791/borrow-inputs"
    assert smoke["params"]["chainBankRepayInputProviderUrl"] == "http://127.0.0.1:8791/repay-inputs"
    assert smoke["params"]["chainBankReserveSignerUrl"] == "http://127.0.0.1:8791/sign"
    assert "chainBankDebtTypeCodeHash" in smoke["queryString"]
    assert smoke["url"].startswith("http://127.0.0.1:8766/?chainBank=1")

    prod_config = FixtureConfig(
        script_params={
            "chainBankDebtTypeCodeHash": "0x" + ("aa" * 32),
            "chainBankBookLockCodeHash": "0x" + ("bb" * 32),
            "chainBankCollateralLockCodeHash": "0x" + ("cc" * 32),
            "chainBankReserveLockCodeHash": "0x" + ("dd" * 32),
            "chainBankTreasuryLockCodeHash": "0x" + ("ee" * 32),
            "chainBankDebtTypeDepTxHash": "0x" + ("ff" * 32),
            "chainBankDebtTypeDepIndex": "0",
        },
        borrow_input_provider_url="https://bank.example/borrow-inputs",
        repay_input_provider_url="https://bank.example/repay-inputs",
        reserve_signer_url="https://bank.example/sign",
        production_smoke=True,
        bank_reserve_cells=[{
            "outPoint": {"txHash": "0x" + ("12" * 32), "index": 0},
            "amount": 100000,
        }],
        require_deployment_values=True,
    )
    assert production_smoke_issues(prod_config) == []
    prod_smoke = smoke_config(prod_config)
    assert prod_smoke["params"]["chainBankScriptMode"] == "production"
    assert prod_smoke["params"]["chainBankBorrowInputProviderUrl"] == "https://bank.example/borrow-inputs"
    assert prod_smoke["params"]["chainBankReserveSignerUrl"] == "https://bank.example/sign"

    bad_prod = FixtureConfig(production_smoke=True)
    assert "placeholder-chainBankDebtTypeCodeHash" in production_smoke_issues(bad_prod)
    bad_values = replace(prod_config, bank_reserve_cells=[])
    assert "missing-funded-bank-reserve-cell" in production_smoke_issues(bad_values)
    print("bank reserve signer fixture self-test passed")
    return 0


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--reserve-tx-hash", default=DEFAULT_RESERVE_TX_HASH)
    parser.add_argument("--reserve-index", type=int, default=DEFAULT_RESERVE_INDEX)
    parser.add_argument("--reserve-amount-ckb", type=float, default=DEFAULT_RESERVE_AMOUNT_CKB)
    parser.add_argument("--collateral-tx-hash", default=DEFAULT_COLLATERAL_TX_HASH)
    parser.add_argument("--collateral-index", type=int, default=DEFAULT_COLLATERAL_INDEX)
    parser.add_argument("--debt-tx-hash", default=DEFAULT_DEBT_TX_HASH)
    parser.add_argument("--debt-index", type=int, default=DEFAULT_DEBT_INDEX)
    parser.add_argument("--locked-collateral-tx-hash", default=DEFAULT_LOCKED_COLLATERAL_TX_HASH)
    parser.add_argument("--locked-collateral-index", type=int, default=DEFAULT_LOCKED_COLLATERAL_INDEX)
    parser.add_argument(
        "--script-params-json",
        default="",
        help="JSON object or {params:{...}} containing deployed chainBank* script params for /smoke-params.",
    )
    parser.add_argument(
        "--deployment-values-json",
        default="",
        help="Unified deployment values JSON containing params, backend URLs, and funded outpoints.",
    )
    parser.add_argument(
        "--bank-input-provider-url",
        default="",
        help="Shared production BORROW/REPAY input provider URL for /smoke-params.",
    )
    parser.add_argument(
        "--bank-borrow-input-provider-url",
        default="",
        help="Production BORROW input provider URL for /smoke-params.",
    )
    parser.add_argument(
        "--bank-repay-input-provider-url",
        default="",
        help="Production REPAY input provider URL for /smoke-params.",
    )
    parser.add_argument(
        "--bank-reserve-signer-url",
        default="",
        help="Production bank reserve signer URL for /smoke-params.",
    )
    parser.add_argument(
        "--production-smoke",
        action="store_true",
        help="Require explicit production backend URLs and non-placeholder script params.",
    )
    parser.add_argument(
        "--validate-production-smoke",
        action="store_true",
        help="Validate production smoke config, print the smoke bundle JSON, and exit.",
    )
    parser.add_argument(
        "--write-smoke-report",
        default="",
        help="Write a redacted testnet smoke execution report JSON and exit.",
    )
    parser.add_argument("--token", default="")
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    if args.self_test:
        return self_test()

    try:
        deployment_values = load_deployment_values(args.deployment_values_json)
        script_params = script_params_from_json(deployment_values, "deployment-values-json") if deployment_values else dict(SMOKE_SCRIPT_PARAMS)
        if args.script_params_json:
            script_params = load_script_params(args.script_params_json)
    except (OSError, ValueError, json.JSONDecodeError) as err:
        print(f"Invalid deployment config: {err}", file=sys.stderr)
        return 2

    input_provider_url = args.bank_input_provider_url or backend_value(deployment_values, "inputProviderUrl")
    borrow_input_provider_url = args.bank_borrow_input_provider_url or backend_value(deployment_values, "borrowInputProviderUrl")
    repay_input_provider_url = args.bank_repay_input_provider_url or backend_value(deployment_values, "repayInputProviderUrl")
    reserve_signer_url = args.bank_reserve_signer_url or backend_value(deployment_values, "reserveSignerUrl")
    token = args.token or backend_value(deployment_values, "token")

    config = FixtureConfig(
        host=args.host,
        port=args.port,
        reserve_tx_hash=args.reserve_tx_hash.lower(),
        reserve_index=args.reserve_index,
        reserve_amount_ckb=args.reserve_amount_ckb,
        collateral_tx_hash=args.collateral_tx_hash.lower(),
        collateral_index=args.collateral_index,
        debt_tx_hash=args.debt_tx_hash.lower(),
        debt_index=args.debt_index,
        locked_collateral_tx_hash=args.locked_collateral_tx_hash.lower(),
        locked_collateral_index=args.locked_collateral_index,
        script_params=script_params,
        input_provider_url=input_provider_url,
        borrow_input_provider_url=borrow_input_provider_url,
        repay_input_provider_url=repay_input_provider_url,
        reserve_signer_url=reserve_signer_url,
        production_smoke=args.production_smoke,
        bank_reserve_cells=deployment_cells(deployment_values, "bankReserveCells", "reserveCells"),
        borrower_collateral_cells=deployment_cells(deployment_values, "borrowerCollateralCells", "collateralCells"),
        require_deployment_values=bool(args.deployment_values_json),
        token=token,
    )
    if config.production_smoke or args.validate_production_smoke or args.write_smoke_report:
        issues = production_smoke_issues(config)
        if issues:
            print("Invalid production smoke config:", ", ".join(issues), file=sys.stderr)
            return 2
    if args.write_smoke_report:
        smoke = smoke_config(replace(config, production_smoke=True))
        try:
            with open(args.write_smoke_report, "w", encoding="utf-8") as handle:
                json.dump(smoke_execution_report(replace(config, production_smoke=True), smoke), handle, indent=2, sort_keys=True)
                handle.write("\n")
        except OSError as err:
            print(f"Unable to write smoke report: {err}", file=sys.stderr)
            return 2
        if not args.validate_production_smoke:
            print(f"Wrote testnet smoke report: {args.write_smoke_report}")
            return 0
    if args.validate_production_smoke:
        print(json.dumps(smoke_config(replace(config, production_smoke=True)), indent=2, sort_keys=True))
        return 0

    server = FixtureServer((config.host, config.port), FixtureHandler, config)
    print(f"Cellshire bank reserve signer fixture listening on http://{config.host}:{config.port}")
    print(f"  reserve inputs: http://{config.host}:{config.port}/reserve-inputs")
    print(f"  borrow inputs:  http://{config.host}:{config.port}/borrow-inputs")
    print(f"  repay inputs:   http://{config.host}:{config.port}/repay-inputs")
    print(f"  smoke params:   http://{config.host}:{config.port}/smoke-params")
    print(f"  signer URL:     http://{config.host}:{config.port}/sign")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping bank reserve signer fixture")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
