#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Install selected Cellshire SFX into the game assets directory.

Workflow:

1. After ``run_cellshire_sfx_batch.py`` produces candidates in
   ``tmp/sfx-generation/<clip-id>/seed<N>.wav``, pick the winner per clip.
2. Record the picks in this file's ``SFX_SELECTIONS`` table.
3. Run ``python3 scripts/install_cellshire_sfx.py`` to copy the chosen
   wavs into ``assets/sfx/<clip-id>.ogg``, converting to Ogg/Vorbis for
   compact in-game delivery via the existing audio pipeline (matching
   the format of the current shipped SFX).

The script also emits a ``loadCellshireSfx()`` JS snippet listing the
``registerClip`` lines, so Codex can wire the new clips into
``src/ui/Audio.js`` without manual book-keeping.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TMP_ROOT = ROOT / "tmp" / "sfx-generation-audiogen"
ASSETS_SFX = ROOT / "assets" / "sfx"


@dataclass(frozen=True)
class SfxSelection:
    """One installed clip — clip_id maps to seed<seed>.wav in tmp_root."""
    clip_id: str
    seed: int
    layer: str
    min_interval_ms: int = 35


# Populate after reviewing tmp/sfx-generation/contact-sheet.md.
# Each entry says "for clip X, use seed Y from the candidates".
# Until selections are made, this list stays empty and the script no-ops.
SFX_SELECTIONS: list[SfxSelection] = [
    SfxSelection("wood_chop",        3102, "harvest",  min_interval_ms=35),
    SfxSelection("stone_strike",     3104, "harvest",  min_interval_ms=35),
    SfxSelection("crop_harvest",     3105, "harvest",  min_interval_ms=35),
    SfxSelection("herb_pluck",       3105, "harvest",  min_interval_ms=25),
    SfxSelection("mine_strike",      3203, "mining",   min_interval_ms=35),
    SfxSelection("mine_deplete",     3203, "mining",   min_interval_ms=35),
    SfxSelection("ore_yield",        3203, "mining",   min_interval_ms=25),
    SfxSelection("craft_success",    3302, "crafting", min_interval_ms=35),
    SfxSelection("tool_upgrade",     3302, "crafting", min_interval_ms=35),
    SfxSelection("building_unlock",  3305, "crafting", min_interval_ms=35),
    SfxSelection("recipe_fail",      3304, "crafting", min_interval_ms=25),
    SfxSelection("coin_chime",       3401, "economy",  min_interval_ms=25),
    SfxSelection("coin_shuffle",     3403, "economy",  min_interval_ms=35),
    SfxSelection("loan_borrow",      3405, "economy",  min_interval_ms=35),
    SfxSelection("loan_repay",       3404, "economy",  min_interval_ms=35),
    SfxSelection("purchase_done",    3407, "economy",  min_interval_ms=35),
    SfxSelection("portal_whoosh",    3503, "travel",   min_interval_ms=35),
    SfxSelection("arrive_mine",      3502, "travel",   min_interval_ms=35),
    SfxSelection("arrive_property",  3504, "travel",   min_interval_ms=35),
    SfxSelection("arrive_township",  3505, "travel",   min_interval_ms=35),
    SfxSelection("tier_unlock",      3603, "property", min_interval_ms=35),
    SfxSelection("save_success",     3604, "property", min_interval_ms=25),
    SfxSelection("toast_success",    3701, "ui",       min_interval_ms=15),
    SfxSelection("toast_error",      3703, "ui",       min_interval_ms=15),
    SfxSelection("toast_info",       3703, "ui",       min_interval_ms=15),
    SfxSelection("wallet_connect",   3706, "ui",       min_interval_ms=25),
    SfxSelection("modal_open",       3705, "ui",       min_interval_ms=25),
    SfxSelection("footstep_grass",   3802, "player",   min_interval_ms=15),
    SfxSelection("footstep_stone",   3804, "player",   min_interval_ms=15),
    SfxSelection("shift_change",     3903, "epoch",    min_interval_ms=35),
    SfxSelection("high_value_sting", 3904, "epoch",    min_interval_ms=35),
]


def have_ffmpeg() -> bool:
    return shutil.which("ffmpeg") is not None


def convert_to_ogg(src_wav: Path, dst_ogg: Path) -> None:
    """Convert WAV → Ogg/Vorbis at quality 4 (~96 kbps mono).
    This matches the size/quality envelope of the existing shipped SFX."""
    dst_ogg.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-loglevel",
            "error",
            "-i",
            str(src_wav),
            "-c:a",
            "libvorbis",
            "-q:a",
            "4",
            str(dst_ogg),
        ],
        check=True,
    )


def render_js_snippet(selections: list[SfxSelection]) -> str:
    lines = [
        "// Auto-generated by scripts/install_cellshire_sfx.py — add to src/ui/Audio.js",
        "// inside loadUiAudio() (or a new loadCellshireSfx()) and wire play* wrappers.",
        "await Promise.all([",
    ]
    for sel in selections:
        lines.append(
            f"  registerClip({sel.clip_id!r:<22}, 'sfx/{sel.clip_id}.ogg',"
            f" {{ minIntervalMs: {sel.min_interval_ms} }}),"
        )
    lines.append("]);")
    return "\n".join(lines)


def main() -> int:
    if not SFX_SELECTIONS:
        print("No selections recorded yet — review tmp/sfx-generation/contact-sheet.md")
        print("then edit SFX_SELECTIONS in this file and re-run.")
        return 0

    if not have_ffmpeg():
        print("ERROR: ffmpeg not found on PATH. Install ffmpeg first.", file=sys.stderr)
        return 1

    converted = 0
    missing: list[SfxSelection] = []
    for sel in SFX_SELECTIONS:
        src = TMP_ROOT / sel.clip_id / f"seed{sel.seed}.wav"
        if not src.exists():
            missing.append(sel)
            continue
        dst = ASSETS_SFX / f"{sel.clip_id}.ogg"
        convert_to_ogg(src, dst)
        rel = dst.relative_to(ROOT)
        print(f"  ✓ {sel.clip_id:20s} → {rel}")
        converted += 1

    if missing:
        print()
        for sel in missing:
            print(f"  ✗ missing seed wav for {sel.clip_id} seed={sel.seed}")
        return 2

    print()
    print(f"Installed {converted} clips into {ASSETS_SFX.relative_to(ROOT)}/")
    print()
    print("JS snippet for src/ui/Audio.js:")
    print()
    print(render_js_snippet(SFX_SELECTIONS))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
